import type { User } from './user.interface';
import type { Chat } from './chat.interface';
import type { MessageEntity } from './message-entity.interface';
import type { Audio } from './audio.interface';
import type { Document } from './document.interface';
import type { Animation } from './animation.interface';
import type { Game } from './game.interface';
import type { PhotoSize } from './photo-size.interface';
import type { Sticker } from './sticker.interface';
import type { Video } from './video.interface';
import type { Voice } from './voice.interface';
import type { VideoNote } from './video-note.interface';
import type { Contact } from './contact.interface';
import type { Location } from './location.interface';
import type { Venue } from './venue.interface';
import type { Poll } from './poll.interface';
import type { Invoice } from './invoice.interface';
import type { SuccessfulPayment } from './successful-payment.interface';
import type { PassportData } from './passport-data.interface';
import type { InlineKeyboardMarkup } from './inline-keyboard-markup.interface';
import type { WebAppData } from './web-app-data.interface';
import type { Dice } from './dice.interface';

export interface Message {
	message_id: string;
	from?: User;
	date: number;
	chat: Chat;
	sender_chat?: Chat;
	forward_from?: User;
	forward_from_chat?: Chat;
	forward_from_message_id?: string;
	forward_signature?: string;
	forward_sender_name?: string;
	forward_date?: number;
	reply_to_message?: Message;
	edit_date?: number;
	media_group_id?: string;
	author_signature?: string;
	text?: string;
	entities?: MessageEntity[];
	caption_entities?: MessageEntity[];
	audio?: Audio;
	document?: Document;
	animation?: Animation;
	game?: Game;
	photo?: PhotoSize[];
	sticker?: Sticker;
	video?: Video;
	voice?: Voice;
	video_note?: VideoNote;
	caption?: string;
	contact?: Contact;
	location?: Location;
	venue?: Venue;
	poll?: Poll;
	new_chat_members?: User[];
	left_chat_member?: User;
	new_chat_title?: string;
	new_chat_photo?: PhotoSize[];
	delete_chat_photo?: boolean;
	group_chat_created?: boolean;
	supergroup_chat_created?: boolean;
	channel_chat_created?: boolean;
	migrate_to_chat_id?: number;
	migrate_from_chat_id?: string;
	pinned_message?: Message;
	invoice?: Invoice;
	successful_payment?: SuccessfulPayment;
	connected_website?: string;
	passport_data?: PassportData;
	reply_markup?: InlineKeyboardMarkup;
	web_app_data?: WebAppData;
	is_automatic_forward?: boolean;
	has_protected_content?: boolean;
	dice?: Dice;
}
